services:
  guesser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guesser-app
    ports:
      - "4102:4102"
    environment:
      NODE_ENV: development
      PORT: 4102
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
